"""Terraform files for the synthetic estate (SYNTHETIC_ESTATE §3); plans offline, empty state."""

from __future__ import annotations

from emissiongate.core.hcl import Attr, Block, q, qlist, render_file
from emissiongate.core.regions import provider_alias

HEADER = (
    "# synthetic: true - generated by `emissiongate estate`. Not real infrastructure; plans never\n"
    "# contact AWS (dummy credentials, no data sources, local state only)."
)
AMI_X86 = "ami-00000000000000086"
AMI_ARM = "ami-000000000000000a4"


def tf_name(resource_id: str) -> str:
    return resource_id.replace("-", "_")


def _tag_blocks(tags: dict[str, str]) -> list[Block | None]:
    out: list[Block | None] = []
    for key in sorted(tags):
        out.append(None)
        out.append(
            Block(
                "tag",
                body=(
                    Attr("key", q(key)),
                    Attr("value", q(tags[key])),
                    Attr("propagate_at_launch", "true"),
                ),
            )
        )
    return out


def _tags_map(tags: dict[str, str]) -> Block:
    # rendered as `tags = { ... }` via a pseudo-block named "tags ="
    return Block("tags =", body=tuple(Attr(k, q(tags[k])) for k in sorted(tags)))


def providers_tf(regions: list[str]) -> str:
    def settings(region: str) -> tuple[Attr, ...]:
        return (
            Attr("region", q(region)),
            Attr("access_key", q("synthetic")),
            Attr("secret_key", q("synthetic")),
            Attr("skip_credentials_validation", "true"),
            Attr("skip_requesting_account_id", "true"),
            Attr("skip_metadata_api_check", "true"),
            Attr("skip_region_validation", "true"),
        )

    blocks = [Block("provider", ("aws",), settings(regions[0]))]
    for region in sorted(regions):
        blocks.append(
            Block(
                "provider", ("aws",), (Attr("alias", q(provider_alias(region))), *settings(region))
            )
        )
    return render_file(blocks, HEADER)


def variables_tf() -> str:
    blocks = [
        Block(
            "variable",
            ("ami_x86_64",),
            (
                Attr("description", q("Synthetic AMI id for x86_64 launch templates.")),
                Attr("type", "string"),
                Attr("default", q(AMI_X86)),
            ),
        ),
        Block(
            "variable",
            ("ami_arm64",),
            (
                Attr("description", q("Synthetic AMI id for arm64 (Graviton) launch templates.")),
                Attr("type", "string"),
                Attr("default", q(AMI_ARM)),
            ),
        ),
    ]
    return render_file(blocks, HEADER)


def asg_blocks(
    resource_id: str,
    region: str,
    instance_type: str,
    count: int,
    tags: dict[str, str],
    arch: str = "x86_64",
    desired: int | None = None,
) -> list[Block]:
    name = tf_name(resource_id)
    provider = f"aws.{provider_alias(region)}"
    lt = Block(
        "resource",
        ("aws_launch_template", name),
        (
            Attr("provider", provider),
            Attr("name", q(f"eg-{resource_id}")),
            Attr("image_id", "var.ami_arm64" if arch == "arm64" else "var.ami_x86_64"),
            Attr("instance_type", q(instance_type)),
        ),
    )
    desired = count if desired is None else desired
    asg = Block(
        "resource",
        ("aws_autoscaling_group", name),
        (
            Attr("provider", provider),
            Attr("name", q(f"eg-{resource_id}")),
            Attr("availability_zones", qlist([f"{region}a", f"{region}b"])),
            Attr("min_size", str(min(desired, count))),
            Attr("max_size", str(count)),
            Attr("desired_capacity", str(desired)),
            None,
            Block(
                "launch_template",
                body=(
                    Attr("id", f"aws_launch_template.{name}.id"),
                    Attr("version", q("$Latest")),
                ),
            ),
            *_tag_blocks(tags),
        ),
    )
    return [lt, asg]


def schedule_block(
    resource_id: str,
    suffix: str,
    region: str,
    recurrence: str,
    time_zone: str,
    size: int,
    action_name: str | None = None,
) -> Block:
    name = tf_name(resource_id)
    return Block(
        "resource",
        ("aws_autoscaling_schedule", f"{name}_{suffix}"),
        (
            Attr("provider", f"aws.{provider_alias(region)}"),
            Attr("scheduled_action_name", q(action_name or f"{resource_id}-{suffix}")),
            Attr("autoscaling_group_name", f"aws_autoscaling_group.{name}.name"),
            Attr("recurrence", q(recurrence)),
            Attr("time_zone", q(time_zone)),
            Attr("min_size", str(0 if size == 0 else size)),
            Attr("max_size", str(size)),
            Attr("desired_capacity", str(size)),
        ),
    )


def rds_block(resource_id: str, region: str, instance_class: str, tags: dict[str, str]) -> Block:
    return Block(
        "resource",
        ("aws_db_instance", tf_name(resource_id)),
        (
            Attr("provider", f"aws.{provider_alias(region)}"),
            Attr("identifier", q(f"eg-{resource_id}")),
            Attr("engine", q("postgres")),
            Attr("instance_class", q(instance_class)),
            Attr("allocated_storage", "500"),
            Attr("username", q("synthetic_admin")),
            Attr("manage_master_user_password", "true"),
            Attr("skip_final_snapshot", "true"),
            None,
            _tags_map(tags),
        ),
    )


def ebs_block(
    resource_id: str, region: str, count: int, size_gb: int, vol_type: str, tags: dict[str, str]
) -> Block:
    return Block(
        "resource",
        ("aws_ebs_volume", tf_name(resource_id)),
        (
            Attr("provider", f"aws.{provider_alias(region)}"),
            Attr("count", str(count)),
            Attr("availability_zone", q(f"{region}a")),
            Attr("size", str(size_gb)),
            Attr("type", q(vol_type)),
            None,
            _tags_map(tags),
        ),
    )


def s3_block(resource_id: str, region: str, tags: dict[str, str]) -> Block:
    return Block(
        "resource",
        ("aws_s3_bucket", tf_name(resource_id)),
        (
            Attr("provider", f"aws.{provider_alias(region)}"),
            Attr("bucket", q(f"eg-synthetic-{resource_id}")),
            None,
            _tags_map(tags),
        ),
    )


def file_text(blocks: list[Block]) -> str:
    return render_file(blocks, HEADER)
